### ISSUE TITLE
"ServerlessError: This plugin could not be found: serverless-optimizer-plugin"

### ISSUE THREAD

**Issue by marclar** [serverless/serverless-starter#11]
Got this error on `sls project install serverless-starter`.

(The error's in the title -- unfortunately the screencast didn't record when I scrolled up to show the error message).

[![asciicast](https://asciinema.org/a/30u97n1sm9vojhosknpfvp4ke.png)](https://asciinema.org/a/30u97n1sm9vojhosknpfvp4ke?speed=2)

**Comment by jolks** [comment]
Having same problem. The above by @marclar happens when one uses Node v5. I tried with Node v4.4.1 and I got this error instead, `TypeError: Class extends value #<Serverless> is not a function or null`

<img width="1065" alt="screen shot 2016-03-23 at 4 40 56 pm" src="https://cloud.githubusercontent.com/assets/765292/13978641/16e5af92-f116-11e5-8163-947245a9d325.png">

**Comment by keyclipse** [comment]
plus one with this error....  do we have to use a specific node js version or is there missing dependencies here....

**Comment by adriandfriend** [comment]
Also having this error, on Node v5

**Comment by hemc4** [comment]
I just ran this command to install serverless-starter and got the same error.
  `serverless project install serverless-starter
`
I am using node v4.2.2
![serverless_error](https://cloud.githubusercontent.com/assets/2142827/14061039/b752758c-f39b-11e5-96a3-639ae3ffbdae.png)

**Comment by jolks** [comment]
@keyclipse @mynameisadrian we have to use [Node v4](https://github.com/serverless/serverless#getting-started). With the latest version of serverless-starter, this problem was fixed.

@hemendra619 Please delete your existing serverless-starter folder and run the installation again.

For reference, this issue is also related to https://github.com/serverless/serverless-starter/issues/12

**Comment by hemc4** [comment]
Thanks @jolks It is working fine with V4.4.1
